######################################################################
# Automatically generated by qmake (3.0) Wed Dec 11 21:48:54 2013
######################################################################

TEMPLATE = app
TARGET = quit
INCLUDEPATH += .
QT += opengl

# Input
SOURCES += quit.cpp
