######################################################################
# Automatically generated by qmake (3.0) Wed Dec 11 23:01:38 2013
######################################################################

TEMPLATE = app
TARGET = find
INCLUDEPATH += .
QT += core gui opengl

# Input
HEADERS += find.h
SOURCES += find.cpp main.cpp
