######################################################################
# Automatically generated by qmake (3.0) Thu Dec 12 14:14:21 2013
######################################################################

TEMPLATE = app
TARGET = sort
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
