######################################################################
# Automatically generated by qmake (3.0) Wed Dec 11 21:59:25 2013
######################################################################

TEMPLATE = app
TARGET = age
INCLUDEPATH += .
QT += opengl

# Input
SOURCES += age.cpp
