######################################################################
# Automatically generated by qmake (3.0) Thu Dec 12 17:19:30 2013
######################################################################

TEMPLATE = app
TARGET = utc-gui
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += utcDialog.h
FORMS += utcDialog.ui
SOURCES += main.cpp utcDialog.cpp
