######################################################################
# Automatically generated by qmake (3.0) Thu Dec 12 11:28:02 2013
######################################################################

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
