######################################################################
# Automatically generated by qmake (3.0) Wed Dec 18 21:23:05 2013
######################################################################

TEMPLATE = app
TARGET = snake
INCLUDEPATH += .

QT += opengl

# Input
HEADERS += mainwindow.h snake.h debug.h nut.h node.h
SOURCES += main.cpp mainwindow.cpp snake.cpp nut.cpp
