######################################################################
# Automatically generated by qmake (3.0) Wed Dec 11 17:39:52 2013
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
QT += opengl

# Input
SOURCES += hello.cpp
